// LAYERPITCH_HELP — dictionnaire des bulles d'aide contextuelle du backstage.
// Séparé de layerpitch-i18n.js volontairement : ce fichier contient du contenu pédagogique
// (explique CE QUE FAIT un contrôle et POURQUOI), pas la traduction de l'interface.
//
// Édité via l'outil dédié (layerpitch-help-editor.html), jamais à la main directement.
// Chargé uniquement par layerpitch-backstage.html — jamais publié sur les pages publiques.
//
// Structure : une zone par section du backstage. Chaque clé correspond à un attribut
// data-help="clé" posé sur un contrôle du backstage.
window.LAYERPITCH_HELP = {
  fr: {
    library: {
      trackMode: "Détermine comment ce morceau réagit à l'écoute : Statique pour une piste simple, Layering vertical additif pour des couches qui s'ajoutent selon l'intensité, Layering vertical randomisé pour une variation aléatoire à chaque écoute, Séquentiel pour un enchaînement intro / segments / outro.",
      loopableStatic: "Coche si ce morceau statique doit boucler en continu (ambiance). Décoché, il joue une fois puis s'arrête — adapté à un thème ou un générique.",
      bpmMeasuresVerticalRandom: "Le tempo et la mesure de ce morceau, utilisés pour caler la grille de la boucle. Nécessaires ici car ce mode boucle toujours selon cette grille rythmique, pour garder la couche fixe et les tirages aléatoires synchronisés entre eux.",
      loopPointsVerticalRandom: "Ces repères définissent où la boucle commence et se termine dans le fichier. Toutes les couches (fixe et alternatives) doivent avoir exactement la même durée pour rester synchronisées.",
      defaultLoopCount: "Nombre de fois que la boucle joue par défaut à l'ouverture de la page publique. Le visiteur pourra changer cette valeur lui-même — ce n'est qu'un point de départ.",
      maxChainLoops: "Combien de fois la chaîne complète (intro comprise, une seule fois, puis segments) se répète avant de basculer automatiquement vers l'outro (ou la fin naturelle sans outro) — équivalent à cliquer \"Aller vers la fin\" tout seul, au bon moment. Le visiteur pourra changer cette valeur lui-même sur la page publique.",
      maxChainLoopsVerticalRandom: "Combien de fois un cycle complet (toutes les sections jouables, chacune une fois) se répète avant de basculer automatiquement vers l'outro (ou la fin naturelle sans outro) — équivalent à cliquer \"Aller vers la fin\" tout seul, au bon moment. Indépendant du nombre de boucles propre à chaque section, réglé plus bas sur chaque section. Le visiteur pourra changer ces deux réglages lui-même sur la page publique.",
      bpmMeasuresSequential: "Le tempo et la mesure de ce morceau. Ils déterminent la durée programmée (en mesures) de l'intro et de chaque segment — voir plus bas. Le fichier peut être plus long que ces mesures : la fin sonne en fondu pendant que le bloc suivant démarre déjà (même principe que le moteur de bouclage quantifié).",
      segmentSlotsSection: "Des emplacements enchaînés dans l'ordre défini (1, 2, 3, ... puis retour au premier), en boucle jusqu'à l'outro. Chaque emplacement peut avoir plusieurs alternatives : une est tirée au hasard à chaque passage sur cet emplacement, plutôt qu'un contenu fixe. Il en faut au moins un pour que le morceau soit jouable.",
      slotRepeatCount: "Combien de fois cet emplacement rejoue (en tirant une nouvelle alternative à chaque fois) avant de passer au suivant dans la chaîne. 1 par défaut — augmente pour une structure du genre AABA où le même emplacement doit tourner plusieurs fois de suite.",
      slotContentSource: "Un emplacement peut soit avoir son propre contenu, soit dupliquer (référencer) le pool d'un autre emplacement déjà défini — utile pour une structure comme AABA sans avoir à recharger deux fois les mêmes fichiers en mémoire. L'anti-répétition est alors partagée entre les deux occurrences.",
      loopEngine: "Simple coupe et relance le fichier instantanément à chaque boucle (parfait pour une boucle déjà parfaitement calée). Quantifié permet une transition plus douce, calée sur le tempo, avec une queue sonore qui continue pendant que la boucle suivante démarre déjà.",
      bpmMeasuresQuantized: "Le tempo et la mesure de ce morceau, nécessaires pour caler la boucle quantifiée sur la grille rythmique plutôt que de couper au sample près.",
      loopPointsQuantized: "Ces repères définissent l'intro (jouée une fois), la boucle, et la queue de fin qui se superpose au redémarrage de la boucle suivante.",
      trackDescription: "Texte affiché sur la page publique sous ce morceau, visible quand le visiteur déplie la piste. Sélectionne du texte puis Cmd+K pour y insérer un lien.",
      normalizeVolume: "Corrige automatiquement les écarts de volume entre les fichiers de ce morceau à la conversion (mesure RMS). Utile si tes couches ou alternatives viennent de sessions différentes et sonnent à des niveaux inégaux. Décoché par défaut : sans ça, tes fichiers sonnent exactement à leur volume d'origine.",
      fixedLayers: "Les couches qui jouent à chaque cycle de boucle, sans exception — c'est ici que vit l'intro et le cœur rythmique du morceau. Elles doivent toutes faire la même durée que les groupes aléatoires ci-dessous.",
      randomGroups: "Chaque groupe tire au hasard une de ses alternatives à chaque cycle de boucle — c'est ce qui donne l'impression que le morceau ne sonne jamais exactement pareil deux fois. Un groupe peut n'avoir qu'une seule alternative si tu veux juste réserver l'emplacement pour plus tard.",
      groupContentSource: "Un groupe peut soit avoir son propre contenu, soit dupliquer (référencer) le pool d'un autre groupe déjà défini — évite de recharger deux fois les mêmes fichiers en mémoire si deux groupes doivent varier de façon identique. L'anti-répétition est alors partagée entre les deux.",
      batchDropSequential: "Dépose plusieurs fichiers d'un coup : leur rôle (intro / segment / outro) est deviné depuis leur nom de fichier. Vérifie ensuite avec le sélecteur \"Rôle\" de chaque bloc, et corrige si besoin.",
      introSection: "Joue une seule fois, au tout début du morceau, avant que le tirage aléatoire des segments ne démarre.",
      outroSection: "Ne se déclenche que si le visiteur clique sur \"Aller vers la fin\" côté public. Sans outro définie, ce bouton laisse simplement le segment en cours filer jusqu'à sa fin naturelle.",
      layersVertical: "Les couches de ce morceau, de la plus calme à la plus intense — c'est cet ordre qui détermine ce qui s'ajoute quand le visiteur augmente l'intensité sur la page publique.",
      stingers: "Sons courts (Sfx) que le visiteur peut déclencher à la main pendant la lecture (ex. un impact, un sting d'alerte), en plus de la musique en cours — n'affectent pas la boucle principale.",
      sfxRrMode: "Comment choisir parmi les variations de ce Sfx à chaque déclenchement. \"Aléatoire\" évite de rejouer deux fois de suite la même variation ; \"Dans l'ordre\" les fait défiler une par une, en boucle.",
      sfxDuck: "Quand ce Sfx joue, le morceau en cours (musique) baisse brièvement de volume pour le mettre en valeur, puis remonte — indépendant des autres réglages de ce morceau.",
      sfxAlternatives: "Les fichiers audio de ce Sfx — un seul suffit, plusieurs permettent d'éviter l'effet de répétition à l'oreille sur un son souvent déclenché.",
      implementationNote: "Note libre à ton attention, reprise telle quelle dans la fiche d'implémentation du pack (onglet Packs). Peut contenir du jargon spécifique à un moteur si tu veux (ex. suggestion de RTPC) — contrairement au reste de la fiche, générée en langage neutre.",
      noAiCertification: "Réglage global pour tout ton catalogue. Coché, une petite icône discrète apparaît sur la page publique — un seul badge à côté de \"Musique\" si tout un bloc est certifié, sinon un par morceau certifié. Chaque morceau peut individuellement faire exception à ce réglage (voir sa propre fiche, plus bas dans sa carte).",
      noAiOverride: "Par défaut, un morceau suit le réglage global. Choisis \"Toujours certifier\" ou \"Ne jamais certifier\" pour faire une exception explicite sur ce morceau précis, indépendamment du réglage global.",
      bpmMeasuresEmbrVert: "Le tempo et la mesure de ce morceau, partagés par toutes les boucles ci-dessous — c'est ce qui leur permet de rester calées les unes sur les autres pendant la lecture, quelle que soit celle audible à un instant donné.",
      embrLoopsSection: "Des boucles nommées et autonomes, qui jouent toutes simultanément en arrière-plan (silencieuses sauf celle active) — le visiteur bascule entre elles en cliquant sur un bouton, avec un fondu court et immédiat. La boucle de référence détermine la longueur du cycle partagé.",
      slotHasBranches: "Au lieu d'avancer automatiquement vers l'emplacement suivant, cet emplacement affiche des boutons côté public et attend un choix du visiteur pour savoir où aller ensuite. Utile pour une structure ramifiée (ex. victoire / défaite) plutôt qu'une simple chaîne linéaire.",
      embrLoopInitial: "Une seule boucle à la fois peut être la référence — c'est elle qui est active par défaut à l'ouverture, et sa longueur en mesures sert de repère pour savoir si les autres boucles peuvent tourner en continu (même longueur) ou seulement en aller-retour ponctuel (plus courtes).",
      slotQuantization: "Détermine QUAND la bascule choisie par le visiteur prend effet une fois cliquée : tout de suite (coupe l'emplacement en cours immédiatement), au prochain temps, ou à la prochaine mesure. S'applique à tous les embranchements sortants de cet emplacement — comme la règle de quantification d'un Transition Object dans Wwise.",
      slotCutStyle: "Comment l'emplacement en cours se termine au moment de la bascule : une coupure nette (identique à Wwise), un fondu très court de 0.15s pour éviter un clic numérique audible, ou une durée personnalisée si tu veux un fondu plus long (par exemple pour laisser le temps à un fichier de transition de s'installer). S'applique quel que soit ce qui suit (fichier de transition ou bascule directe).",
      slotCustomCutFade: "Durée du fondu de sortie de l'emplacement qu'on quitte, en secondes réelles (pas en mesures — un fondu de sortie n'a pas besoin d'être quantifié musicalement). Utile en particulier avec un fichier de transition assez long : un fondu trop court laisserait la source couper sec pendant que la transition continue de s'installer dessus.",
      branchTransition: "Un fichier joué juste après la coupure et avant que la cible ne démarre — l'équivalent d'un Transition Object Wwise pour CETTE paire précise (cet embranchement, pas l'emplacement entier). Chaque embranchement peut avoir son propre fichier de transition, ou aucun.",
      transitionDurationUnit: "Durée nominale du fichier de transition avant que le fondu-enchaînement classique vers la cible ne prenne le relais. En mesures : la transition peut avoir son propre tempo (BPM/temps par mesure), différent de celui de l'emplacement source — utile pour un impact ou un riser qui n'est pas dans le tempo du morceau. En secondes : durée brute, sans notion de tempo, pour un fichier non quantifié musicalement.",
      stageDescription: "Texte affiché à la place de la description du morceau pendant que CET élément précis (cet emplacement, cette intro/outro, ce fichier de transition) est effectivement audible — utile pour donner un contexte narratif qui change au fil de la lecture (ex. le nom du lieu traversé). Laissé vide dans les deux langues : n'écrase rien, le texte précédemment affiché reste tel quel — pratique pour ne renseigner ce champ que sur les éléments qui ont vraiment quelque chose à dire, sans devoir le répéter partout.",
      slotBpmOverride: "Laisse vide pour suivre le tempo du morceau (réglé plus haut) — utile seulement si CET emplacement doit sonner à un tempo différent des autres (ex. une section calme à 90 BPM dans un morceau à embranchement par ailleurs à 140 BPM). S'applique à la durée programmée de ses propres segments, et — pour un embranchement sortant de cet emplacement — à la frontière de coupure, qui suit toujours le tempo de l'emplacement qu'on QUITTE. Le fichier de transition, lui, suit ce même tempo par défaut mais peut définir le sien (voir sa propre durée avant bascule).",
    },
    packs: {
      packIllustration: "Image principale affichée en haut de la page publique de ce pack.",
      packWatermark: "Image de fond décorative affichée en transparence derrière tout le contenu de la page — purement esthétique, optionnelle.",
      packPresentation: "Texte de présentation affiché sur la page publique du pack, au-dessus de la liste des morceaux, quand ce pack est lié à un AdReel en français. Sélectionne du texte puis Cmd+K pour y insérer un lien.",
      packPresentationEn: "Version anglaise du texte ci-dessus, affichée quand ce pack est lié à un AdReel en anglais. Si l'une des deux langues n'est pas remplie, l'autre s'affiche par défaut.",
      packFreeDownload: "Fait apparaître un vrai bouton de téléchargement sur la page publique du pack — génère un zip avec tous les fichiers audio publiés des morceaux inclus, directement dans le navigateur du visiteur. Fonctionne dès maintenant, aucune configuration supplémentaire.",
      collectionFreeDownload: "Fait apparaître un vrai bouton de téléchargement sur la page publique de la collection — génère un zip avec tous les fichiers audio publiés de tous les morceaux de tous les packs inclus, directement dans le navigateur du visiteur. Fonctionne dès maintenant, aucune configuration supplémentaire.",
      packBuyable: "Réglage préparatoire pour plus tard — pendant la bêta, la page publique du pack affiche toujours la vente comme \"Bientôt disponible\", même si cette case est cochée, pour ne jamais laisser croire à un système de paiement qui n'existe pas encore.",
      collectionBuyable: "Affiche un bouton d'achat sur la page publique de la collection, indépendamment de celui de chaque pack qui la compose. Aucun paiement réel n'est traité aujourd'hui — le lien peut pointer vers autre chose en attendant (mail, formulaire) si besoin.",
      packVideoTestMode: "Ajoute un bouton pour tester une vidéo YouTube/Vimeo : intégrée directement sur la page si le visiteur n'a qu'un écran, ou dans une fenêtre séparée et détachable s'il en a plusieurs. Son coupé par défaut (le visiteur peut le réactiver), pour que le visiteur teste tes morceaux en direct dessus pendant qu'il regarde.",
      implementationSkills: "Réglage global pour tout le site, pas par pack. Coche les logiciels que tu maîtrises (Wwise, FMOD, Unity, Unreal) : un message le mentionnant apparaît sur la page publique de chaque pack, listant uniquement ceux cochés. Aucune case cochée = aucun message affiché.",
      implementationSheetBtn: "Génère à la volée un document (texte + JSON) décrivant le comportement musical de chaque morceau de ce pack en langage neutre — nombre de couches, seuils d'intensité, BPM, points de boucle, structure intro/segment/outro selon le mode. Rien n'est stocké ni publié, uniquement généré au moment où tu cliques.",
      collectionIllustration: "Image principale affichée en haut de la page publique de cette collection.",
      collectionPresentation: "Texte de présentation affiché sur la page publique de la collection, au-dessus de la liste des packs qu'elle contient, quand elle est liée à un AdReel en français.",
      collectionPresentationEn: "Version anglaise du texte ci-dessus. Si l'une des deux langues n'est pas remplie, l'autre s'affiche par défaut.",
      collectionPacks: "Les packs inclus dans cette collection, dans l'ordre d'affichage sur sa page publique. Un même pack peut appartenir à plusieurs collections.",
      packAppearance: "Couleurs de fond et de texte propres à la page de ce pack — indépendantes de celles de l'AdReel qui y renvoie.",
      packTracks: "Les morceaux de la bibliothèque inclus dans ce pack, dans l'ordre d'affichage sur sa page publique.",
      packSfx: "Les Sfx de la Bibliothèque Sfx inclus dans ce pack. Le genre affiché à côté du titre du pack (Musique/Sfx/Hybride) se calcule automatiquement selon ce que tu mets ici et dans les morceaux — rien à régler toi-même.",
      packLinkedAdReel: "Utile si tu envoies ce pack seul à un prospect (par mail, par exemple), sans passer par un AdReel complet — le visiteur verra un lien vers l'AdReel choisi pour découvrir le reste de ton travail et te contacter.",
      publishToSocial: "Ouvre la fenêtre de publication du réseau choisi, avec le texte et le lien déjà prêts — il reste à cliquer sur \"Publier\" chez eux. Aucune publication automatique : configure tes réseaux dans l'onglet dédié pour faire apparaître des boutons ici.",
    },
    appearance: {
      publishLang: "Langue de l'interface publique pour cet AdReel — n'affecte pas ton contenu (titres, textes, témoignages), qui reste dans la langue où tu l'as écrit. Les packs liés depuis cet AdReel suivent automatiquement ce choix.",
      bgColorAppearance: "Couleur de fond de la page publique de cet AdReel. Vérifie le contraste avec les couleurs de texte pour rester lisible. Réglage général — chaque bloc peut le personnaliser individuellement plus bas.",
      titleColorAppearance: "Couleur des titres sur la page publique de cet AdReel. Réglage général — chaque bloc peut le personnaliser individuellement plus bas.",
      contentColorAppearance: "Couleur du texte de contenu sur la page publique de cet AdReel. Réglage général — chaque bloc peut le personnaliser individuellement plus bas.",
      fontAppearance: "Police utilisée pour le contenu de la page publique de cet AdReel. Réglage général — chaque bloc peut le personnaliser individuellement plus bas. Les polices personnalisées se gèrent dans la section \"Polices personnalisées\" juste en dessous.",
      bgImageAppearance: "Image de fond de la page publique de cet AdReel. Réglage général — chaque bloc peut avoir sa propre image de fond, indépendante de celle-ci.",
      bgImageOpacityAppearance: "Opacité de l'image de fond générale (0 = invisible, 1 = pleinement visible). N'affecte pas la lisibilité du texte, qui reste régie par les couleurs de police choisies.",
    },
    github: {
      ghOwner: "Ton nom d'utilisateur ou d'organisation GitHub — visible dans l'URL de ton repo (github.com/OWNER/repo).",
      ghRepo: "Le nom du dépôt GitHub où ce site est hébergé — visible dans l'URL (github.com/owner/REPO).",
      ghBranch: "La branche du dépôt à lire et publier — \"main\" dans la grande majorité des cas, à ne changer que si ton repo utilise un nom de branche différent.",
      ghToken: "Un token d'accès personnel GitHub (\"Fine-grained\", limité à ce seul dépôt) qui autorise ce backstage à publier à ta place. Retenu localement sur cet ordinateur (fichier ouvert en local, jamais servi ni publié) — à recoller seulement si tu changes d'ordinateur ou vides ton navigateur.",
    },
    content: {
      formspreeEndpoint: "L'URL de ton formulaire Formspree — nécessaire uniquement si tu ajoutes un bloc \"Contact\" à une page. Sans ça, ce bloc n'affichera rien côté public.",
      blockAlign: "Position de ce bloc sur la page publique. S'applique uniquement si le bloc ne contient qu'un seul élément (une image) ; avec plusieurs images, elles s'affichent en grille quel que soit ce réglage.",
      headerTitle: "Ton nom ou celui de ton studio — affiché en grand, avec ou sans logo au-dessus. Sa police et sa couleur suivent le réglage \"Couleur police des titres\" et la police choisie dans l'onglet Apparence (personnalisables aussi pour ce bloc précis, section \"Apparence de ce bloc\" plus bas).",
      headerSubtitle: "Courte phrase sous le titre — ta spécialité ou ton positionnement en une ligne.",
      headerLogo: "Ton logo, affiché en haut de la page. Sans logo, ton nom s'affiche en toutes lettres à la place.",
      headerContactEmail: "Affiché en bas de page si renseigné — indépendant du bloc \"Contact\" (formulaire), qui est optionnel.",
      headerWebsite: "Ton site web, affiché en bas de page si renseigné.",
      bioPhoto: "Photo affichée à côté de ton texte de présentation, dans ses proportions réelles (pas de recadrage forcé).",
      bioText: "Ton texte de présentation. Sépare les paragraphes par une ligne vide pour qu'ils s'affichent distinctement.",
      tracksBlockSelector: "Ce bloc affiche les morceaux sélectionnés ici, dans cet ordre, sur la page publique. Le contenu de chaque morceau (fichiers, description) se gère dans la Bibliothèque — ici tu choisis juste lesquels et dans quel ordre.",
      trackOverride: "Coche pour donner à ce morceau un titre/texte différent uniquement pour cet AdReel, sans toucher à la version de référence dans la Bibliothèque — utile par ex. pour une version dans une autre langue. Décoché, le texte de la Bibliothèque s'affiche tel quel.",
      videoLink: "Un lien YouTube ou Vimeo s'intègre automatiquement en vignette cliquable sur la page publique. Un autre type de lien (Dropbox, etc.) s'affiche comme un simple lien externe.",
      videoThumbnail: "Image affichée à la place de la vignette par défaut (générée automatiquement pour YouTube, absente sinon). Optionnel.",
    },
    misc: {
      feedbackBtn: "Envoie un message directement à Jules-Antoine — bugs, confusions, idées, ce qui t'a plu ou pas. Pas besoin d'être structuré.",
      backstageBgColor: "Change uniquement le fond de cet écran d'édition, pour ton confort visuel — n'a aucun effet sur ce que voient tes visiteurs. Mémorisé sur cet ordinateur seulement.",
      modeTestToggle: "Coche pendant que tu testes toi-même l'outil (démonstration, vérification) — tes actions ne compteront pas dans les statistiques d'usage réel des testeurs. Décoche pour ton usage normal.",
    },
  },
  en: {
    library: {
      trackMode: "Determines how this track behaves for the listener: Static for a single track, Additive vertical layering for layers that build up with intensity, Randomized vertical layering for variation on every listen, Sequential for an intro / segments / outro flow.",
      loopableStatic: "Check if this static track should loop continuously (ambience). Unchecked, it plays once and stops — suited to a theme or credits.",
      bpmMeasuresVerticalRandom: "This track's tempo and time signature, used to set the loop grid. Required here because this mode always loops on that rhythmic grid, to keep the fixed layer and the random draws synced with each other.",
      loopPointsVerticalRandom: "These markers define where the loop starts and ends in the file. All layers (fixed and alternatives) must have exactly the same duration to stay in sync.",
      defaultLoopCount: "How many times the loop plays by default when the public page opens. Visitors can change this themselves — it's only a starting point.",
      maxChainLoops: "How many times the complete chain (intro included, only once, then segments) repeats before automatically switching to the outro (or the natural end without one) — equivalent to clicking \"Go to end\" on your behalf, at the right moment. Visitors can change this themselves on the public page.",
      maxChainLoopsVerticalRandom: "How many times a full cycle (every playable section, each once) repeats before automatically switching to the outro (or the natural end without one) — equivalent to clicking \"Go to end\" on your behalf, at the right moment. Independent from each section's own loop count, set further down per section. Visitors can change both of these themselves on the public page.",
      bpmMeasuresSequential: "This track's tempo and time signature. They determine the planned length (in bars) of the intro and each segment — see below. The file can be longer than those bars: the end fades out while the next block already starts (same principle as the quantized looping engine).",
      segmentSlotsSection: "Slots chained in the defined order (1, 2, 3, ... then back to the first), looping until the outro. Each slot can have several alternatives: one is drawn at random each time playback reaches that slot, rather than fixed content. At least one is needed for the track to be playable.",
      slotRepeatCount: "How many times this slot replays (drawing a new alternative each time) before moving to the next one in the chain. 1 by default — raise it for an AABA-like structure where the same slot needs to run several times in a row.",
      slotContentSource: "A slot can either have its own content, or duplicate (reference) another slot's pool that's already defined — useful for an AABA-like structure without loading the same files into memory twice. Repeat-avoidance is then shared between the two occurrences.",
      loopEngine: "Simple cuts and restarts the file instantly on every loop (fine for a loop that's already perfectly seamless). Quantized allows a smoother, tempo-locked transition, with a sound tail that keeps ringing while the next loop has already started.",
      bpmMeasuresQuantized: "This track's tempo and time signature, needed to align the quantized loop to the rhythmic grid instead of cutting at an arbitrary sample.",
      loopPointsQuantized: "These markers define the intro (played once), the loop, and the tail that overlaps as the next loop starts.",
      trackDescription: "Text shown on the public page under this track, visible when the visitor expands it. Select text then Cmd+K to insert a link.",
      normalizeVolume: "Automatically corrects volume differences between this track's files at conversion time (RMS measurement). Useful if your layers or alternatives come from different sessions and play back at uneven levels. Unchecked by default: without it, your files play back at their original volume.",
      fixedLayers: "The layers that play on every loop cycle, without exception — this is where the intro and rhythmic backbone of the track live. They must all have the same duration as the random groups below.",
      randomGroups: "Each group randomly draws one of its alternatives on every loop cycle — this is what makes the track never sound exactly the same twice. A group can have just one alternative if you simply want to reserve the slot for later.",
      groupContentSource: "A group can either have its own content, or duplicate (reference) another group's pool that's already defined — avoids loading the same files into memory twice if two groups need to vary identically. Repeat-avoidance is then shared between the two.",
      batchDropSequential: "Drop several files at once: their role (intro / segment / outro) is guessed from the filename. Double-check with each block's \"Role\" selector afterwards, and fix it if needed.",
      introSection: "Plays once, right at the start of the track, before the random segment draw begins.",
      outroSection: "Only triggers if the visitor clicks \"Go to ending\" on the public side. Without an outro set, this button simply lets the current segment run to its natural end.",
      layersVertical: "This track's layers, from calmest to most intense — this order determines what gets added as the visitor increases the intensity on the public page.",
      stingers: "Short sounds (Sfx) the visitor can trigger manually during playback (e.g. a hit, an alert sting), layered on top of the ongoing music — they don't affect the main loop.",
      sfxRrMode: "How to pick among this Sfx's variations each time it's triggered. \"Random\" avoids playing the same variation twice in a row; \"In order\" cycles through them one by one, looping back to the start.",
      sfxDuck: "When this Sfx plays, the ongoing track (music) briefly lowers in volume to bring it forward, then comes back up — independent from that track's other settings.",
      sfxAlternatives: "The audio files for this Sfx — one is enough, several help avoid a repetitive feel for a sound that gets triggered often.",
      implementationNote: "Free note for your own use, reused as-is in the pack's implementation sheet (Packs tab). Can contain engine-specific jargon if you want (e.g. a suggested RTPC) — unlike the rest of the sheet, which is generated in neutral language.",
      noAiCertification: "Global setting for your whole catalog. When checked, a small discreet icon appears on the public page — a single badge next to \"Music\" if a whole block is certified, otherwise one per certified track. Each track can individually make an exception to this setting (see its own sheet, further down in its card).",
      noAiOverride: "By default, a track follows the global setting. Choose \"Always certify\" or \"Never certify\" to make an explicit exception for this specific track, independent of the global setting.",
      bpmMeasuresEmbrVert: "The tempo and time signature of this track, shared by all the loops below — this is what keeps them in sync with each other during playback, whichever one is audible at any given moment.",
      embrLoopsSection: "Named, self-contained loops that all play simultaneously in the background (silent except for the active one) — the visitor switches between them by clicking a button, with a short, immediate crossfade. The reference loop sets the shared cycle length.",
      slotHasBranches: "Instead of automatically advancing to the next slot, this slot shows buttons on the public page and waits for the visitor to choose where to go next. Useful for a branching structure (e.g. victory / defeat) rather than a simple linear chain.",
      embrLoopInitial: "Only one loop at a time can be the reference — it's the one active by default on load, and its length in bars is the yardstick for whether the other loops can run continuously (same length) or only as a one-off detour (shorter).",
      slotQuantization: "Determines WHEN the visitor's chosen switch actually takes effect once clicked: right away (cuts the current slot immediately), on the next beat, or on the next bar. Applies to all of this slot's outgoing branches — like a Transition Object's quantization rule in Wwise.",
      slotCutStyle: "How the current slot ends at the moment of the switch: a hard cut (matches Wwise), a very short 0.15s fade to avoid an audible digital click, or a custom duration if you want a longer fade (for example to give a transition file time to settle in). Applies regardless of what follows (a transition file or a direct switch).",
      slotCustomCutFade: "Fade-out duration for the slot being left, in real seconds (not bars — a fade-out doesn't need to be musically quantized). Especially useful with a fairly long transition file: too short a fade would leave the source cutting sharply while the transition is still settling in on top of it.",
      branchTransition: "A file played right after the cut and before the target starts — the equivalent of a Wwise Transition Object for THIS specific pair (this branch, not the whole slot). Each branch can have its own transition file, or none at all.",
      transitionDurationUnit: "Nominal duration of the transition file before the classic crossfade into the target takes over. In bars: the transition can have its own tempo (BPM/beats per bar), different from the source slot's — useful for an impact or riser that isn't in the track's tempo. In seconds: raw duration, no tempo involved, for a file that isn't musically quantized.",
      stageDescription: "Text shown instead of the track description while THIS specific element (this slot, this intro/outro, this transition file) is actually audible — useful for narrative context that changes as playback progresses (e.g. the name of the location being crossed). Left blank in both languages: overwrites nothing, the previously shown text stays as is — handy for only filling this in on the elements that actually have something to say, without repeating it everywhere.",
      slotBpmOverride: "Leave blank to follow the track's tempo (set above) — only useful if THIS slot needs to sound at a different tempo than the others (e.g. a calm section at 90 BPM inside an otherwise 140 BPM branching track). Applies to the planned length of its own segments, and — for a branch leaving this slot — to the cut boundary, which always follows the tempo of the slot being LEFT. The transition file follows that same tempo by default, but can set its own (see its own duration before switching).",
    },
    packs: {
      packIllustration: "Main image shown at the top of this pack's public page.",
      packWatermark: "Decorative background image shown as a transparent overlay behind all the page content — purely aesthetic, optional.",
      packPresentation: "Presentation text shown on the pack's public page, above the track list, when this pack is linked to a French AdReel. Select text then Cmd+K to insert a link.",
      packPresentationEn: "English version of the text above, shown when this pack is linked to an English AdReel. If one of the two languages isn't filled in, the other is shown by default.",
      packFreeDownload: "Shows a real download button on the pack's public page — generates a zip with all the published audio files of the included tracks, right in the visitor's browser. Works right away, no extra setup needed.",
      collectionFreeDownload: "Shows a real download button on the collection's public page — generates a zip with all the published audio files of every track in every included pack, right in the visitor's browser. Works right away, no extra setup needed.",
      packBuyable: "A preparatory setting for later — during the beta, the pack's public page always shows purchasing as \"Coming soon\", even if this box is checked, so it never looks like a payment system that doesn't exist yet.",
      collectionBuyable: "Shows a buy button on the collection's public page, independent of each individual pack's own buy button. No real payment is processed today — the link can point to something else in the meantime (email, form) if needed.",
      packVideoTestMode: "Adds a button to test a YouTube/Vimeo video: embedded right on the page if the visitor has a single screen, or in a separate detachable window if they have several. Muted by default (the visitor can turn sound back on), so the visitor can test your tracks live against it while watching.",
      implementationSkills: "Global setting for the whole site, not per pack. Check the software you're proficient with (Wwise, FMOD, Unity, Unreal): a message mentioning it appears on each pack's public page, listing only the checked ones. No box checked = no message shown.",
      implementationSheetBtn: "Generates on the fly a document (text + JSON) describing the musical behavior of each track in this pack in neutral language — number of layers, intensity thresholds, BPM, loop points, intro/segment/outro structure depending on mode. Nothing is stored or published, only generated the moment you click.",
      collectionIllustration: "Main image shown at the top of this collection's public page.",
      collectionPresentation: "Presentation text shown on the collection's public page, above the list of packs it contains, when linked to a French AdReel.",
      collectionPresentationEn: "English version of the text above. If one of the two languages isn't filled in, the other is shown by default.",
      collectionPacks: "The packs included in this collection, in the order they're shown on its public page. The same pack can belong to several collections.",
      packAppearance: "Background and text colors specific to this pack's page — independent from those of the AdReel linking to it.",
      packTracks: "The library tracks included in this pack, in the order they're shown on its public page.",
      packSfx: "The Sfx from the Sfx library included in this pack. The kind shown next to the pack's title (Music/Sfx/Hybrid) is computed automatically from what you put here and in the tracks — nothing to set yourself.",
      packLinkedAdReel: "Useful if you send this pack on its own to a prospect (by email, for example), without going through a full AdReel — the visitor will see a link to the chosen AdReel to discover the rest of your work and reach out to you.",
      publishToSocial: "Opens the chosen network's publish window, with the text and link already ready — all that's left is to click \"Post\" on their end. No automatic posting: set up your networks in the dedicated tab to get buttons here.",
    },
    appearance: {
      publishLang: "The public interface language for this AdReel — doesn't affect your own content (titles, texts, testimonials), which stays in the language you wrote it in. Packs linked from this AdReel automatically follow this choice.",
      bgColorAppearance: "Background color of this AdReel's public page. Check the contrast against the text colors to stay readable. General setting — any block can override it individually below.",
      titleColorAppearance: "Title color on this AdReel's public page. General setting — any block can override it individually below.",
      contentColorAppearance: "Content text color on this AdReel's public page. General setting — any block can override it individually below.",
      fontAppearance: "Font used for the public page content of this AdReel. General setting — any block can override it individually below. Custom fonts are managed in the \"Custom fonts\" section just below.",
      bgImageAppearance: "Background image for this AdReel's public page. General setting — any block can have its own background image, independent from this one.",
      bgImageOpacityAppearance: "Opacity of the general background image (0 = invisible, 1 = fully visible). Doesn't affect text readability, which stays governed by the chosen text colors.",
    },
    github: {
      ghOwner: "Your GitHub username or organization — visible in your repo's URL (github.com/OWNER/repo).",
      ghRepo: "The name of the GitHub repository hosting this site — visible in the URL (github.com/owner/REPO).",
      ghBranch: "The repo branch to read from and publish to — \"main\" in the vast majority of cases, only change it if your repo uses a different branch name.",
      ghToken: "A GitHub personal access token (\"Fine-grained\", scoped to this one repository) that lets this backstage publish on your behalf. Kept locally on this computer (a file opened locally, never served or published) — only needs re-pasting if you switch computers or clear your browser data.",
    },
    content: {
      formspreeEndpoint: "Your Formspree form URL — only needed if you add a \"Contact\" block to a page. Without it, that block will show nothing on the public side.",
      blockAlign: "This block's position on the public page. Only applies if the block contains a single item (one image); with several images, they're shown as a grid regardless of this setting.",
      headerTitle: "Your name or your studio's — shown large, with or without a logo above it. Its font and color follow the \"Title text color\" setting and the font chosen in the Appearance tab (also customizable for this specific block, \"Appearance of this block\" section below).",
      headerSubtitle: "Short line under the title — your specialty or positioning in one sentence.",
      headerLogo: "Your logo, shown at the top of the page. Without one, your name is shown spelled out instead.",
      headerContactEmail: "Shown at the bottom of the page if filled in — independent from the \"Contact\" block (form), which is optional.",
      headerWebsite: "Your website, shown at the bottom of the page if filled in.",
      bioPhoto: "Photo shown next to your bio text, in its real proportions (no forced cropping).",
      bioText: "Your bio text. Separate paragraphs with a blank line so they display as distinct blocks.",
      tracksBlockSelector: "This block shows the tracks selected here, in this order, on the public page. Each track's content (files, description) is managed in the Library — here you're just choosing which ones and in what order.",
      trackOverride: "Check to give this track a different title/text just for this AdReel, without touching the reference version in the Library — useful e.g. for a version in another language. Unchecked, the Library text is shown as-is.",
      videoLink: "A YouTube or Vimeo link automatically embeds as a clickable thumbnail on the public page. Any other kind of link (Dropbox, etc.) shows as a plain external link instead.",
      videoThumbnail: "Image shown instead of the default thumbnail (auto-generated for YouTube, absent otherwise). Optional.",
    },
    misc: {
      feedbackBtn: "Sends a message straight to Jules-Antoine — bugs, confusing bits, ideas, what you liked or didn't. No need to be structured about it.",
      backstageBgColor: "Only changes the background of this editing screen, for your own visual comfort — has no effect on what your visitors see. Remembered on this computer only.",
      modeTestToggle: "Check while you're testing the tool yourself (demo, verification) — your actions won't count toward real testers' usage stats. Uncheck for normal use.",
    },
  },
};
